### PR TITLE
build: major paragon and react-intl version upgrade

### PR DESCRIPTION
**Pull request by Syed-Ali-Abbas-Zaidi**
Major version upgrade of `@edx/paragon` and `react-intl`.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Syed-Ali-Abbas-Zaidi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @Syed-Ali-Abbas-Zaidi! Thanks for this contribution. As with the other pull requests, please submit your [CLA](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base) and we'll get these through for you!

**Comment by e0d** [comment]
@mphilbrick211 tests running

**Comment by openedx-webhooks** [comment]
@Syed-Ali-Abbas-Zaidi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-portal-programs&entry.867055334=https://github.com/openedx/frontend-app-learner-portal-programs/pull/266&entry.1484655318=https://github.com/Syed-Ali-Abbas-Zaidi&entry.752974735=2023-02-13+11:19&entry.1917517419=2023-02-22+07:13&entry.2133058324=No) so we can improve your experience in the future.

**Comment by mphilbrick211** [comment]
Hi @Syed-Ali-Abbas-Zaidi - is this pull request ready for review?

**Comment by Syed-Ali-Abbas-Zaidi** [comment]
> Hi @Syed-Ali-Abbas-Zaidi - is this pull request ready for review?

Hi @mphilbrick211 - Yes it is ready for review.

**Comment by mphilbrick211** [comment]
Hi @chennighan2u! Would you mind taking a look at this for review/merge? Thank you!

**Comment by mphilbrick211** [comment]
> Hi @chennighan2u! Would you mind taking a look at this for review/merge? Thank you!

Hi @chennighan2u! Friendly ping on this.

**Review by schenedx — APPROVED** [review]
👍

**Review by alangsto — APPROVED** [review]

**Pull request merged**
